### ISSUE TITLE
Error: constexpr function return is non-constant

### ISSUE THREAD

**Issue by anilsathyan7** [AngusG/tensorflow-xnor-bnn#10]
We got the following error when we ran the make command:-

lib/python3.6/site-packages/tensorflow/include/absl/strings/string_view.h(496): error: constexpr function return is non-constant

**Comment by anilsathyan7** [comment]
Solved by adding -DNDEBUG in Makefile with nvcc commands.

**Comment by anilsathyan7** [comment]
It seems to work with cuda-9.0 and tensorflow 1.12  with the following changes 
1. Makefile g++ command : g++ -std=c++11 -shared -o libs/gemm_op.so src/gemm_op.cc -D_GLIBCXX_USE_CXX11_ABI=0 obj/xnor_gemm_kernel.cu.o obj/base_gemm_kernel.cu.o obj/concatenate_kernel.cu.o -I ${TF_INC} -fPIC -lcudart -I ${TF_INC}/external/nsync/public -L ${TF_LIB} -ltensorflow_framework -L ${CUDA_ROOT}/lib64)
2. In setenv.sh. add : export TF_LIB=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())')
